apiVersion: v1
kind: Service
metadata:
  name: {{ include "vapi.fullname" . }}
  labels:
    {{- include "vapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30510
      protocol: TCP
      name: http
  selector:
    {{- include "vapi.selectorLabels" . | nindent 4 }}
